# Cloud Build configuration for Worker Service v2
# Uses asia-southeast2 Artifact Registry (compliant with org policy)

steps:
  # Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'asia-southeast2-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/text-doc-worker-service-v2:$COMMIT_SHA',
      '-t', 'asia-southeast2-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/text-doc-worker-service-v2:latest',
      '.'
    ]
    id: 'build-worker-service'

  # Push image with commit SHA
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'asia-southeast2-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/text-doc-worker-service-v2:$COMMIT_SHA']
    id: 'push-worker-service'
    waitFor: ['build-worker-service']

  # Push latest tag
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'asia-southeast2-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/text-doc-worker-service-v2:latest']
    id: 'push-worker-service-latest'
    waitFor: ['build-worker-service']

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args: [
      'run', 'deploy', 'text-doc-worker-service-v2',
      '--image=asia-southeast2-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/text-doc-worker-service-v2:$COMMIT_SHA',
      '--region=asia-southeast2',
      '--platform=managed'
    ]
    id: 'deploy-worker-service'
    waitFor: ['push-worker-service']

# Store images in Artifact Registry (asia-southeast2 only)
images:
  - 'asia-southeast2-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/text-doc-worker-service-v2:$COMMIT_SHA'
  - 'asia-southeast2-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/text-doc-worker-service-v2:latest'

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'

timeout: '900s'
